version: '3.9'

services:
  db:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  bot:
    container_name: tg_bot
    build: .
    privileged: true
    depends_on:
      - db
